const posters = [
  {
    id: 1,
    title: "화음",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 01_그디_화음.png",
  },
  {
    id: 2,
    title: "요동",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 02_그디_요동.png",
  },
  {
    id: 3,
    title: "소리의 시각화",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 03-그디_소리의 시각화.png",
  },
  {
    id: 4,
    title: "파괴와 재구성",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 04_그디_파괴와 재구성.png",
  },
  {
    id: 5,
    title: "8주차",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 05_그디_8주차.png",
  },
  {
    id: 6,
    title: "추상화",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 06_그디_추상화.png",
  },
  {
    id: 7,
    title: "10주차 I",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 07_그디_10주차.png",
  },
  {
    id: 8,
    title: "10주차 II",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 08_그디_10주차.png",
  },
  {
    id: 9,
    title: "이미지와 스토리 I",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 09_그디_이미지와 스토리.png",
  },
  {
    id: 10,
    title: "이미지와 스토리 II",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 10_그디_이미지와 스토리.png",
  },
  {
    id: 11,
    title: "위계",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 11_그디_위계.png",
  },
  {
    id: 12,
    title: "보색",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 12_그디_보색.png",
  },
];
