const posters = [
  {
    id: 1,
    title: "포스터 제목 1",
    creator: "홍길동",
    year: "2025",
    category: "타이포그래피",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    themeColor: "#1a1a1a",
    description: "이 포스터에 대한 설명을 입력하세요. 작업의 의도와 시각적 실험에 대해 서술합니다.",
    story: "",
    tags: ["타이포그래피", "흑백"],
    imageUrl: "",
  },
  {
    id: 2,
    title: "포스터 제목 2",
    creator: "홍길동",
    year: "2025",
    category: "포스터",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    themeColor: "#1a1a1a",
    description: "이 포스터에 대한 설명을 입력하세요. 작업의 의도와 시각적 실험에 대해 서술합니다.",
    story: "",
    tags: ["레이아웃", "컬러"],
    imageUrl: "",
  },
  {
    id: 3,
    title: "포스터 제목 3",
    creator: "홍길동",
    year: "2025",
    category: "그래픽",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    themeColor: "#1a1a1a",
    description: "이 포스터에 대한 설명을 입력하세요. 작업의 의도와 시각적 실험에 대해 서술합니다.",
    story: "",
    tags: ["그래픽", "실험"],
    imageUrl: "",
  },
];
