const posters = [
  {
    id: 1,
    title: "화음",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "B/W, Basic shapes",
    tool: "Adobe Illustrator",
    description: "불협화음도 화음이다. 각자 고유의 간격을 유지하고 있던 두 모양이 합쳐졌을 때, 무언가 어색한 간격을 이루는 모습은 그것대로 완성이다.",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 01_그디_WK3_화음.png",
  },
  {
    id: 2,
    title: "요동",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "B/W, Basic shapes",
    tool: "Adobe Illustrator",
    description: "프레임에서 벗어나지 못한 채 이리저리 좌우로 움직이는 원의 움직임을 담아보았다.",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 02_그디_WK3_요동.png",
  },
  {
    id: 3,
    title: "First Step",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "B/W, magnificence, space, cold",
    tool: "Adobe Illustrator",
    description: "영화 인터스텔라의 사운드트랙인 Hans Zimmer의 First Step을 시각화했다. 원의 크기로 공간감을 조성하고, 그 사이를 유동적으로 흐르는 선의 집합체로 스트링의 선율을 담았다. 포인트 컬러는 우주의 차가움에서 빌려왔다.",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 03-그디_WK4_소리의 시각화.png",
  },
  {
    id: 4,
    title: "Sharp",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "B/W, Typography",
    tool: "Adobe Illustrator",
    description: "Sharp는 날카롭다는 뜻이지만, 일상에서 가장 흔하게 쥐는 샤프펜슬을 떠올리게 하기도 한다. SHARP의 A를 펜촉으로 형상화해 단어가 스스로를 설명하게 했다.",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 03-그디_WK5_타이포그래피.png",
  },
  {
    id: 5,
    title: "파괴와 재구성",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "B/W, Typography",
    tool: "Adobe Illustrator",
    description: "윤동주 시인의 '별 헤는 밤' 일부를 가져왔다. 별 하나를 통해 수많은 생각을 떠올렸을 시인을 생각하며, 굵은 국문 서체로 별 안에 담긴 생각들을 표현했다.",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 04_그디_WK6_파괴와 재구성.png",
  },
  {
    id: 6,
    title: "100 Beste Plakate",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "420 × 594mm",
    concept: "B/W, typography, basic shapes",
    tool: "Adobe Illustrator",
    description: "매년 DACH 지역에서 열리는 포스터 공모전이자 전시회, 100 Beste Plakate의 전시 포스터를 제작했다. 독일, 오스트리아, 스위스 세 나라의 공통된 컬러인 레드를 포인트 컬러로 사용했고, 여러 겹으로 깔린 포스터의 모습으로 전시의 성격을 드러내고자 했다.",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 05_그디_WK8_Beste Plakate.png",
  },
  {
    id: 7,
    title: "Plant 11",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "simple, abstract, image",
    tool: "Adobe Illustrator",
    description: "추상화 한 그래픽 이미지 사이사이에 놓여있는 타이포를 통해 쌓여있는 떨어지는 나뭇잎을 표현했다.",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 06_그디_WK9_Plant.png",
  },
  {
    id: 8,
    title: "道路工事",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "album art, image",
    tool: "Adobe Photoshop, Adobe Illustrator",
    description: "SHO-SENSEI!!의 도로공사(道路工事)의 가상 앨범 포스터를 작업했다. 제이팝 특유의 청량함을 푸른 바다와 구름으로 나타내보았다.",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 07_그디_WK10_道路工事.png",
  },
  {
    id: 9,
    title: "Hollywoods Bleeding",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "album art, image",
    tool: "Adobe Photoshop, Adobe Illustrator",
    description: "포스트 말론의 앨범 Hollywood's Bleeding 가상 앨범 포스터를 작업했다. 실제 앨범 커버의 어둡고 무거운 분위기에서 벗어나, 수록곡 Sunflower와 노이즈가 섞인 듯한 그의 보컬적 특징에서 착안해 해바라기와 라디오를 합성하여 앨범을 재해석했다.",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 08_그디_WK10_Post Malone.png",
  },
  {
    id: 10,
    title: "サムライハート",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "album art, image",
    tool: "Adobe Photoshop, Adobe Illustrator",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 09_그디_WK11_サムライハート.png",
  },
  {
    id: 11,
    title: "익숙한 낯섬",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "exhibition, image",
    tool: "Adobe Photoshop, Adobe Illustrator",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 10_그디_WK12_익숙한 낯섬.png",
  },
  {
    id: 12,
    title: "Solitude",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "image",
    tool: "Adobe Photoshop, Adobe Illustrator",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 11_그디_WK13_Solitude.png",
  },
  {
    id: 13,
    title: "Vinyl Club",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "297 × 420mm",
    concept: "image",
    tool: "Adobe Photoshop, Adobe Illustrator",
    description: "",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 12_그디_WK13_Vinyl Club.png",
  },
  {
    id: 14,
    title: "DEEP SMOKE",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "420 × 594mm",
    concept: "image, concert",
    tool: "Adobe Photoshop, Adobe Illustrator",
    description: "포스트 말론의 2026 월드 투어를 주제로 한 가상 홍보 포스터를 작업했다. 애연가인 그의 이미지에서 착안해 Deep Smoke를 타이틀로 선정했고, 아티스트의 이미지를 전면에 내세우기 위해 타이포를 최소화했다.",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 13_그디_WK15_자유.png",
  },
  {
    id: 15,
    title: "A Book is a [ ]",
    creator: "Taemok Oh",
    year: "2026",
    medium: "디지털 프린트",
    dimensions: "420 × 594mm",
    concept: "B/W, typography, exhibition",
    tool: "Adobe Photoshop, Adobe Illustrator",
    description: "2026 Unlimited Edition 서울 아트 북 페어의 가상 홍보 포스터를 작업했다. 책장에 꽂힌 책을 타이포로 표현해 전시의 성격을 직접적으로 드러냈고, 디지털보다 아날로그의 감각에 가깝게 만들고자 했다.",
    story: "",
    tags: ["Poster"],
    imageUrl: "images/Poster 13_그디_WK15_주제.png",
  },
];
